version: "2"
services:
  # 0, 1, 2, 3 for network
  frontend:
    build: .
    entrypoint: frontend
    container_name: 'hotel_reserv_frontend'
    ports:
      - "5000:5000"
    # depends_on:
    #   - consul
    restart: always
    cpuset: "4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19"