version: "2.0"
services:
  consul:
    image: consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    restart: always

  frontend:
    image: yz2297/hotel_reservation
    entrypoint: frontend
    ports:
      - "5000:5000"
    depends_on:
      - consul
    volumes:
      - ./config.json:/go/src/github.com/harlow/go-micro-services/config.json
    restart: always
    container_name: hotelreservation_frontend

  profile:
    image: yz2297/hotel_reservation
    entrypoint: profile
    ports:
      - "8081:8081"
    depends_on:
      - consul
    volumes:
      - ./config.json:/go/src/github.com/harlow/go-micro-services/config.json
    restart: always
    container_name: hotelreservation_profile

  geo:
    image: yz2297/hotel_reservation
    entrypoint: geo
    ports:
      - "8083:8083"
    depends_on:
      - consul
    volumes:
      - ./config.json:/go/src/github.com/harlow/go-micro-services/config.json
    restart: always
    container_name: hotelreservation_geo

  rate:
    image: yz2297/hotel_reservation
    entrypoint: rate
    ports:
      - "8084:8084"
    depends_on:
      - consul
    volumes:
      - ./config.json:/go/src/github.com/harlow/go-micro-services/config.json
    restart: always
    container_name: hotelreservation_rate
    
  recommendation:
    image: yz2297/hotel_reservation
    entrypoint: recommendation
    ports:
      - "8085:8085"
    depends_on:
      - consul
    volumes:
      - ./config.json:/go/src/github.com/harlow/go-micro-services/config.json
    restart: always
    container_name: hotelreservation_recommendation

  user:
    image: yz2297/hotel_reservation
    entrypoint: user
    ports:
      - "8086:8086"
    depends_on:
      - consul
    volumes:
      - ./config.json:/go/src/github.com/harlow/go-micro-services/config.json
    restart: always
    container_name: hotelreservation_user
    
  reservation:
    image: yz2297/hotel_reservation
    entrypoint: reservation
    ports:
      - "8087:8087"
    depends_on:
      - consul
    volumes:
      - ./config.json:/go/src/github.com/harlow/go-micro-services/config.json
    restart: always
    container_name: hotelreservation_reservation

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14269"
      - "5778:5778"
      - "14268:14268"
      - "14267"
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
    restart: always

volumes:
  geo:
  profile:
  rate:
  recommendation:
  reservation:
  user: