apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-multi
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-reader
  namespace: {{ .Release.Namespace }}
