apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: base64-app
  name: base64-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: base64-app
  template:
    metadata:
      labels:
        app: base64-app
    spec:
      containers:
      - image: us.icr.io/sample-functions/base64
        imagePullPolicy: Always
        name: base64
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: base64-app
  namespace: default
spec:
  type: NodePort
  selector:
    app: base64-app
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001
